export const FONT_SIZE_DEFAULT = 15;
export const FONT_SIZE_BUTTON = 15;
export const FONT_SIZE_BODY = 15;
export const FONT_SIZE_TITLE = 21;
const LINE_MARGIN = 0.1;
export const FONT_LINE_HEIGHT = FONT_SIZE_DEFAULT + LINE_MARGIN * FONT_SIZE_DEFAULT * 2;
export const FONT_TITLE_LINE_HEIGHT = FONT_SIZE_TITLE + LINE_MARGIN * FONT_SIZE_DEFAULT * 2;
